### ISSUE TITLE
Request: Specify site in random

### ISSUE THREAD

**Issue by dannyisokay** [ishwi/Chuu#54]
Specify a supported platform/site for the random command, example:
!random --bandcamp: brings a bandcamp link

**Comment by ishwi** [comment]
This was implemented in 8fe65a54b7162373d957bcbcec193e092564b768 and the bugs were fixed in 8fe65a54b7162373d957bcbcec193e092564b768

**Comment by dannyisokay** [comment]
Specifying --server and then a site still doesn't work. Sometimes it does but it has a chance of not getting a link
